name: Auto Generate Sitemap

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate_sitemap:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate sitemap
        uses: cicirello/generate-sitemap@v1
        with:
          base-url-path: https://converter.thenepal.io

      - name: Commit sitemap.xml
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add sitemap.xml
          git commit -m "Auto update sitemap" || echo "No changes"
          git push
